u-boot-fw-utils: remove bbappend
The OE-Core project now make use of libubootenv which is board
independent (see [1]).

Fixes:

ERROR: No recipes available for:
  /<path to>/meta-swupdate/recipes-bsp/u-boot/u-boot-fw-utils%.bbappend

So, this commit also drop the libubootenv recipe.

[1] - https://git.openembedded.org/openembedded-core/tree/meta/recipes-bsp/u-boot/libubootenv_0.2.bb

Signed-off-by: Darko Komljenovic <dkomljenovic@zoho.com>
[Pierre-Jean:
    - rework commit log
    - drop git recipe for libubootenv]
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>